name = "torneospokerlive-og"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://www.torneospokerlive.com,http://localhost:3000"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

