-- Migration: Create tournament_stars table
-- Description: Tabla para gestionar los torneos marcados como favoritos por los usuarios
-- Date: 2025-10-04
-- Author: Sistema de favoritos de torneos

-- Crear la tabla tournament_stars
CREATE TABLE IF NOT EXISTS public.tournament_stars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    tournament_id bigint NOT NULL REFERENCES public."Tournament"(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, tournament_id)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_tournament_stars_user_id ON public.tournament_stars(user_id);
CREATE INDEX IF NOT EXISTS idx_tournament_stars_tournament_id ON public.tournament_stars(tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_stars_created_at ON public.tournament_stars(created_at);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.tournament_stars ENABLE ROW LEVEL SECURITY;

-- Política de lectura: Permitir a todos los usuarios autenticados leer
-- (necesario para JOINs en queries de Supabase)
CREATE POLICY "tournament_stars_select_authenticated"
    ON public.tournament_stars
    FOR SELECT
    TO authenticated
    USING (true);

-- Política de inserción: Solo pueden insertar si el user_id coincide con el usuario autenticado
CREATE POLICY "tournament_stars_insert_own"
    ON public.tournament_stars
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

-- Política de eliminación: Solo pueden eliminar sus propios registros
CREATE POLICY "tournament_stars_delete_own"
    ON public.tournament_stars
    FOR DELETE
    TO authenticated
    USING (auth.uid() = user_id);

-- Otorgar permisos explícitos a usuarios autenticados
GRANT SELECT, INSERT, DELETE ON public.tournament_stars TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.tournament_stars_id_seq TO authenticated;

-- Comentarios para documentación
COMMENT ON TABLE public.tournament_stars IS 'Tabla para gestionar los torneos marcados como favoritos por los usuarios';
COMMENT ON COLUMN public.tournament_stars.user_id IS 'ID del usuario que marcó el torneo como favorito';
COMMENT ON COLUMN public.tournament_stars.tournament_id IS 'ID del torneo marcado como favorito';
COMMENT ON COLUMN public.tournament_stars.created_at IS 'Fecha y hora en que se marcó como favorito';

