-- Script SQL para crear la tabla tournament_stars en Supabase
-- Esta tabla gestiona los torneos favoritos de los usuarios

-- Crear la tabla tournament_stars
CREATE TABLE IF NOT EXISTS public.tournament_stars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    tournament_id bigint NOT NULL REFERENCES public."Tournament"(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, tournament_id)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_tournament_stars_user_id ON public.tournament_stars(user_id);
CREATE INDEX IF NOT EXISTS idx_tournament_stars_tournament_id ON public.tournament_stars(tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_stars_created_at ON public.tournament_stars(created_at);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.tournament_stars ENABLE ROW LEVEL SECURITY;

-- Política: Los usuarios autenticados pueden ver todos los registros para hacer JOINs
-- (esto es necesario para las queries con relaciones como tournament:Tournament(*))
CREATE POLICY "Authenticated users can view tournament_stars"
    ON public.tournament_stars
    FOR SELECT
    TO authenticated
    USING (true);

-- Política: Los usuarios pueden insertar sus propios torneos favoritos
CREATE POLICY "Users can insert their own favorite tournaments"
    ON public.tournament_stars
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

-- Política: Los usuarios pueden eliminar sus propios torneos favoritos
CREATE POLICY "Users can delete their own favorite tournaments"
    ON public.tournament_stars
    FOR DELETE
    TO authenticated
    USING (auth.uid() = user_id);

-- Comentarios para documentación
COMMENT ON TABLE public.tournament_stars IS 'Tabla para gestionar los torneos marcados como favoritos por los usuarios';
COMMENT ON COLUMN public.tournament_stars.user_id IS 'ID del usuario que marcó el torneo como favorito';
COMMENT ON COLUMN public.tournament_stars.tournament_id IS 'ID del torneo marcado como favorito';
COMMENT ON COLUMN public.tournament_stars.created_at IS 'Fecha y hora en que se marcó como favorito';

